paths:
  /api/products/:
    get:
      summary: Get a list of products
      tags:
        - Products
      parameters:
        - name: limit
          in: query
          description: Max number of products per page.
          schema:
            type: integer
        - name: sort
          in: query
          description: Product sort order.
          schema:
            type: string
            enum: ["asc", "desc"]
        - name: page
          in: query
          description: Page number for pagination.
          schema:
            type: integer
        - name: query
          in: query
          description: Search term to filter products by category or status
          schema:
            type: string
      responses:
        "200":
          description: Products were fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Internal server error
    post:
      summary: Create a new product (admin or premium)
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/ProductObject"
      responses:
        "201":
          description: The product has been created successfully 
        "500":
          description: Internal server error
  /api/products/{pid}:
    get:
      summary: Get product by id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Get a product by id
          schema:
            type: string
      responses:
        "200":
          description: Product found
        "500":
          description: Internal server error
    put:
      summary: Update a product by id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Product id to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/ProductObject"
      responses:
        "200":
          description: Product has been updated successfully
        "500":
          description: Internal server error
    delete:
      summary: Delete a product by id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Product id to delete
          schema:
            type: string
      responses:
        "200":
          description: Product has been deleted successfully
        "500":
          description: Internal server error

components:
  schemas:
    Product:
      type: Object
      properties:
        _id:
          type: string
          description: Id autogenerated by MongoDB
        title:
          type: string
          description: Product name
        description:
          type: string
          description: Product description
        thumbnails:
          type: array
          items:
            type: string
          description: Image links
        category:
          type: string
          description: Proudct category
        price:
          type: number
          description: Product price
        stock:
          type: integer
          description: Product stock
        status:
          type: boolean
          description: Product status, if is it false is an inactive product
        code:
          type: string
          description: Product code
        owner:
          type: string
          description: Product owner, it can be 'admin' or a user email
      example:
        _id: ObjectId('64611d8c7f508f9cd4ae73b2')
        title: Small Concrete Gloves
        description: The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality.
        thumbnails: []
        category: Music
        price: 123
        stock: 123
        status: true
        code: 978-1-6905-1567-8
        owner: admin
  requestBodies:
    ProductObject:
      type: object
      properties:
        title:
          type: string
          description: Product name
        description:
          type: string
          description: Product description
        thumbnails:
          type: array
          items:
            type: string
          description: Image links
        category:
          type: string
          description: Proudct category
        price:
          type: number
          description: Product price
        stock:
          type: integer
          description: Product stock
        status:
          type: boolean
          description: Product status, if is it false is an inactive product
        code:
          type: string
          description: Product code
        owner:
          type: string
          description: Product owner, it can be 'admin' or a user email
      example:
        title: Small Concrete Gloves
        description: The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality.
        thumbnails: []
        category: Music
        price: 123
        stock: 123
        status: true
        code: 978-1-6905-1567-8
        owner: admin
